# Copyright 2023 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Set fact of 'vmware-vdiskmanager.exe' tool path"
  when:
    - host_machine_type == "windows"
    - dh_host_installed_path is defined and dh_host_installed_path
    #- dh_host_vdisk_manager_path is undefined or not dh_host_vdisk_manager_path
  block:
    - name: "Set vmware-vdiskmanager path"
      ansible.builtin.set_fact:
        dh_host_vdisk_manager_path: "{{ dh_host_installed_path }}\\vmware-vdiskmanager.exe"
    - name: "Check vdiskmanager installed path in Windows host"
      include_tasks: ../../../windows/utils/win_check_file_exist.yml
      vars:
        win_check_file_exist_file: "{{ dh_host_vdisk_manager_path }}"
        vm_guest_ip: "{{ host_machine_hostname }}"
    - name: "Display win_check_file_exist_result"
      ansible.builtin.debug: var=win_check_file_exist_result
      failed_when: not win_check_file_exist_result
    - name: "Set fact of file existence"
      ansible.builtin.set_fact:
        dh_host_vdisk_manager_exists: "{{ win_check_file_exist_result }}"

- name: "Set fact of 'vmware-vdiskmanager' tool path"
  when:
    - host_machine_type == "linux"
    - dh_host_installed
    - dh_host_vdisk_manager_path is undefined or not dh_host_vdisk_manager_path
  block:
    - name: "Get vmware-vdiskmanager installed path in Linux host"
      ansible.builtin.shell: "which vmware-vdiskmanager"
      delegate_to: "{{ host_machine_hostname }}"
      register: lin_software_install_path
    - name: "Set fact of vmware-vdiskmanager installed path"
      ansible.builtin.set_fact:
        dh_host_vdisk_manager_path: "{{ lin_software_install_path.stdout }}"
        dh_host_vdisk_manager_exists: "{{ true if lin_software_install_path.stdout else false }}"