# Copyright 2023-2026 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Check ovftool installed path in Windows Host"
  when:
    - host_machine_type == "windows"
    - dh_host_installed
    - dh_host_installed_path is defined and dh_host_installed_path
  block:
    - name: "Set fact of ovftool installed path"
      ansible.builtin.set_fact:
        dh_host_ovftool_path: "{{ dh_host_installed_path }}\\OVFTool\\ovftool.exe"
        
    - name: "Check ovftool installed path in Windows host"
      include_tasks: ../../../windows/utils/win_check_file_exist.yml
      vars:
        win_check_file_exist_file: "{{ dh_host_ovftool_path }}"
        vm_guest_ip: "{{ host_machine_hostname }}"

    - name: "Assert ovftool exists in Windows"
      ansible.builtin.fail:
        msg: "ovftool is not found at {{ dh_host_ovftool_path }}."
      when: not win_check_file_exist_result

- name: "Check ovftool installed path in Linux host"
  when:
    - host_machine_type == "linux"
    - dh_host_installed
    - dh_host_installed_path is defined and dh_host_installed_path
  block:
    - name: "Get ovftool installed path in Linux host"
      ansible.builtin.command: "which ovftool"
      delegate_to: "{{ host_machine_hostname }}"
      register: lin_software_install_path
      changed_when: false
      ignore_errors: true

    - name: "Assert ovftool exists in Linux"
      ansible.builtin.fail:
        msg: "ovftool is not found in system PATH."
      when: lin_software_install_path.rc != 0
      
    - name: "Set fact of ovftool installed path"
      ansible.builtin.set_fact:
        dh_host_ovftool_path: "{{ lin_software_install_path.stdout }}"
