# Copyright 2023 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Get installed VMware tools version and build number
- name: "Initialize VMware tools version info"
  ansible.builtin.set_fact:
    vmtools_info_from_vmtoolsd: ''

- name: "Get guest vmtools on Windows Host"
  when: host_machine_type == "windows"
  include_tasks: ../windows/utils/get_windows_tools_version.yml

- name: "Get guest vmtools on Linux Host"
  when: host_machine_type == "linux"
  include_tasks: ../linux/utils/get_linux_tools_version.yml

- name: "Set fact of tools version and build number"
  ansible.builtin.set_fact:
    vmtools_info_from_vmtoolsd: "{{ vmtools_version_build.stdout_lines[0] | default('') }}"

- name: "Print VMware Tools version and build"
  ansible.builtin.debug: var=vmtools_info_from_vmtoolsd
