# Copyright 2023-2026 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
# vmrun power operation in Windows/Linux host
# Parameters:
#   vm_power_option: start, stop, reset, suspend, pause, unpause
---
- name: "Initialize extra option"
  ansible.builtin.set_fact:
    vm_extra_option: ""

- name: "Set fact of extra option for start"
  ansible.builtin.set_fact:
    vm_extra_option: "nogui"
  when: vm_power_option == "start"

- name: "Set fact of extra option for other operations"
  ansible.builtin.set_fact:
    vm_extra_option: "{{ vmrun_extra_option | default('hard') }}"
  when: vm_power_option != "start"

- name: "{{ vm_power_option }} VM on windows host"
  include_tasks: win_host_power_vm.yml
  vars:
    power_option: "{{ vm_power_option }}"
  when: host_machine_type == "windows"

- name: "{{ vm_power_option }} VM on linux host"
  include_tasks: lin_host_power_vm.yml
  vars:
    power_option: "{{ vm_power_option }}"
    extra_option: "{{ vm_extra_option }}"
  when: host_machine_type == "linux"

- name: "Pause 30 seconds"
  ansible.builtin.pause:
    seconds: 30
