# Copyright 2021-2023 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Revert to snapshot of VM
# Parameters:
#   snapshot_name: the name of snapshot to revert
#   skip_if_not_exist: if set to true, revert snapshot task will not fail when snapshot doesn't exist.
#   Default value is false.
#
- name: Set fact of revert to snapshot failed if not exist
  when: skip_if_not_exist is undefined
  ansible.builtin.set_fact:
    skip_if_not_exist: false

- name: "Revert to snapshot {{ snapshot_name }} on Windows Host"
  when: host_machine_type == "windows"
  include_tasks: ../../windows/utils/win_execute_cmd.yml
  vars:
    win_powershell_cmd: >-
      Start-Process -FilePath "{{ dh_host_vmrun_path }}" -ArgumentList '-T ws revertToSnapshot "{{ dh_vm_vmx_path }}" "{{ snapshot_name }}"' -NoNewWindow
    vm_guest_ip: "{{ host_machine_hostname }}"
  ignore_errors: true
  register: revert_result

- name: "Revert to snapshot {{ snapshot_name }} on Linux Host"
  when: host_machine_type == "linux"
  ansible.builtin.shell: |
    {{ dh_host_vmrun_path }} -T ws revertToSnapshot {{ dh_vm_vmx_path }} {{ snapshot_name }}
  delegate_to: "{{ host_machine_hostname }}"
  become: true
  become_user: "{{ dh_vm_username }}"
  ignore_errors: true
  register: revert_result
  failed_when:
    - vm_snapshot_facts.stderr is defined
    - vm_snapshot_facts.stderr | length != 0
    - "'Error' in vm_snapshot_facts.stderr"

- name: "Display revert snapshot result"
  when: enable_debug is defined and enable_debug
  ansible.builtin.debug: var=revert_result

- name: "Handle revert snasphot failure"
  when:
    - host_machine_type == "linux"
    - revert_result.stdout
    - "'failed' in revert_result.stdout"
  block:
    - name: "Check snapsphot not exist failure message"
      ansible.builtin.set_fact:
        msg_no_snapshots: "{{ revert_result.stdout | regex_search('does not have any snapshots to revert') }}"
        msg_not_find_snapshot: "{{ revert_result.stdout | regex_search('Couldn't find any snapshots with specified name') }}"

    - name: "Ignore snapshot not exist failure"
      when:
        - skip_if_not_exist
        - msg_no_snapshots or msg_not_find_snapshot
      ansible.builtin.debug:
        msg: "Snapshot '{{ snapshot_name }}' not exist, but 'skip_if_not_exist' is set to True"

    # Other failures
    - name: "Revert snapshot failed"
      ansible.builtin.fail:
        msg: "Revert to snapshot '{{ snapshot_name }}' failed"

#- name: "Get snapshot facts until current snapshot is the expected one after revert to snapshot"
#  when: revert_result.changed
#  include_tasks: dh_vm_wait_expected_snapshot.yml
#  vars:
#    expected_snapshot_name: "{{ snapshot_name }}"

- name: "Start the vm after snapshot revert"
  when: not dh_vm_exists
  include_tasks: dh_host_power_vm.yml
  vars:
    vm_power_option: "start"

