# Copyright 2021-2025 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Uninstall open-vm-tools
# Parameters:
#   ovt_packages: a list of open-vm-tools packages
#
# Uninstall open-vm-tools packages
- name: "Get installed packages on {{ vm_guest_os_distribution }}"
  include_tasks: ../../../linux/utils/get_installed_packages.yml

- name: "Set fact of installed open-vm-tools related packages"
  ansible.builtin.set_fact:
    installed_ovt_packages: "{{ ovt_packages | select('in', guest_installed_packages) }}"

- name: "Display open-vm-tools related packages which are installed in guest OS"
  ansible.builtin.debug: var=installed_ovt_packages

- name: "Uninstall packages {{ ovt_packages }}"
  ansible.builtin.command: "{{ package_uninstall_cmd }} {{ ' '.join(installed_ovt_packages) }}"
  register: ovt_uninstall_result
  ignore_errors: true
  delegate_to: "{{ vm_guest_ip }}"

- name: "Display the packages uninstall output"
  ansible.builtin.debug: var=ovt_uninstall_result
  when: enable_debug | bool

- name: "Assert command is executed successfully"
  ansible.builtin.assert:
    that:
      - ovt_uninstall_result is defined
      - ovt_uninstall_result.stdout is defined
      - ovt_uninstall_result.stdout
      - ovt_uninstall_result.rc is defined
      - ovt_uninstall_result.rc | int == 0
    fail_msg: "Failed to uninstall open-vm-tools by executing command: {{ package_uninstall_cmd }} {{ ' '.join(ovt_packages) }}"
