# Copyright 2023 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
#
# Using vmrun to install choco and firefox
# Open www.vmware.com with firefox
# See more example of vmrun in
# https://docs.vmware.com/en/VMware-Fusion/13/com.vmware.fusion.using.doc/GUID-FF306A59-080E-497E-857D-F45125927FB3.html
#
- name: "Set fact of VNC port"
  when: dh_vm_vnc_port is defined and dh_vm_vnc_port
  ansible.builtin.set_fact:
    display_port: "{{ dh_vm_vnc_port|int - 5900 }}"

- name: "Set fact of VNC port"
  when: dh_vm_vnc_port is not defined or not dh_vm_vnc_port
  ansible.builtin.set_fact:
    display_port: 0

- name: "Set fact of guest user"
  when: new_user is defined and new_user
  ansible.builtin.set_fact:
    autologin_user: "{{ new_user }}"

- name: "Set fact of guest user"
  when: >
    dh_vm_username != "root" or
    new_user is not defined
  ansible.builtin.set_fact:
    autologin_user: "{{ dh_vm_username }}"

- name: "Open www.vmware.com with firefox"
  ansible.builtin.shell: |
    {{ dh_host_vmrun_path }} -gu {{ autologin_user }} -gp {{ dh_vm_password }} runProgramInGuest {{ dh_vm_vmx_path }} -noWait /usr/bin/firefox --display=:{{ display_port }} https://www.vmware.com
  delegate_to: "{{ host_machine_hostname }}"
  become: true
  become_user: "{{ dh_vm_username }}"
  register: vmrun_result
  failed_when:
    - vmrun_result.stderr is defined
    - vmrun_result.stderr | length != 0
    - "'Error' in vmrun_result.stderr"

- name: "Pause 30 seconds"
  ansible.builtin.pause:
    seconds: 30

- name: "Get VNC port"
  ansible.builtin.shell: |
    {{ dh_host_vmrun_path }} -T ws -gu {{ dh_vm_username }} -gp {{ dh_vm_password }} readVariable {{ dh_vm_vmx_path }} runtimeConfig remotedisplay.vnc.port
  register: vnc_port
  delegate_to: "{{ host_machine_hostname }}"
  become: true
  become_user: "{{ dh_vm_username }}"
  async: 120
  poll: 10

- name: "Take a VM screenshot after browser test"
  ansible.builtin.shell: "vncdo -v -s {{ host_machine_hostname }}::{{ vnc_port.stdout_lines[0] }} capture {{ current_test_log_folder }}/vm_screenshot_after_check_browser_test.png"
  register: vncdo_take_screenshot
  async: 120
  poll: 10
  failed_when:
    - vncdo_take_screenshot.stderr is defined
    - "'refused' in vncdo_take_screenshot.stderr"

- name: "Display the vncdotool taking screenshot result"
  ansible.builtin.debug: var=vncdo_take_screenshot
