# Copyright 2023 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Get guest information collected by VMTools
- name: "Get the detailed data of guest on Windows Host"
  ansible.windows.win_command:
    cmd: '"{{ dh_host_vmrun_path }}" -T ws -gu {{ dh_vm_username }} -gp {{ dh_vm_password }} readVariable "{{ dh_vm_vmx_path }}" runtimeConfig guestInfo.detailed.data'
  register: vm_guestinfo
  delay: 20
  retries: "{{ vm_guestinfo_retry_times | default(5) }}"
  until:
    - vm_guestinfo is defined
    - vm_guestinfo.stdout_lines is defined
    - vm_guestinfo.stdout_lines | length != 0
    - "'prettyName' in vm_guestinfo.stdout_lines[0]"
  ignore_errors: true
  delegate_to: "{{ host_machine_hostname }}"

- name: "Print VM guest info"
  ansible.builtin.debug: var=vm_guestinfo
