# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Uninstall VMware Tools firstly when it's installed"
  include_tasks: ../wintools_uninstall_verify/uninstall_vmtools.yml
  when:
    - update_vmtools | bool
    - vmtools_is_installed

- name: "Enable test signing"
  include_tasks: enable_test_signing.yml
  when:
    - is_development_tools is defined
    - is_development_tools | bool

- name: "Set fact of VMware Tools silent install command and getting install log file"
  ansible.builtin.set_fact:
    vmtools_install_cmd: >-
      D:\\{{ wintools_setup_exe }} /S /v "/qn ADDLOCAL=ALL REBOOT=R"
    get_vmtools_install_log: true

# In Windows Server 2012 R2 guest OS, need to set 'become' to run
# VMware Tools install command
- name: "Execute VMware Tools silent install command in guest"
  ansible.windows.win_shell: "{{ vmtools_install_cmd }}"
  delegate_to: "{{ vm_guest_ip }}"
  ignore_errors: true
  become: "{{ guest_os_product_version | int == 2012 }}"
  become_method: runas
  become_user: "{{ 'Administrator' if (guest_os_product_version | int == 2012) else omit }}"
  register: wintools_install_result
  async: 600
  poll: 0
  environment:
    ANSIBLE_WIN_ASYNC_STARTUP_TIMEOUT: 60

- name: "Pause 2 minutes before checking task status"
  ansible.builtin.pause:
    minutes: 2
  when: not (wintools_install_result.failed | default(true))

- name: "Check VMware Tools install task started"
  ansible.builtin.assert:
    that:
      - wintools_install_result is defined
      - wintools_install_result.ansible_job_id is defined
    fail_msg: >-
      The async task of VMware Tools installation in guest OS is not started.
      Task returned message: {{ wintools_install_result.msg | default('') }}.

- name: "Check VMware Tools install task status every 3 seconds"
  ansible.builtin.async_status:
    jid: "{{ wintools_install_result.ansible_job_id }}"
  register: wintools_install_job
  delegate_to: "{{ vm_guest_ip }}"
  ignore_errors: true
  until:
    - wintools_install_job.finished is defined
    - wintools_install_job.finished | int == 1
  retries: 100
  delay: 3
  when:
    - wintools_install_result is defined
    - wintools_install_result.ansible_job_id is defined

- name: "Check VMware Tools install task finished"
  ansible.builtin.assert:
    that:
      - wintools_install_job.finished is defined
      - wintools_install_job.finished | int == 1
    fail_msg: >-
      Failed to get the finished status of VMware Tools install task in guest OS, error message
      '{{ wintools_install_job.msg | default('') }}'

- name: "Pause 30 seconds after VMware Tools install"
  ansible.builtin.pause:
    seconds: 30

- name: "Restart guest OS after VMware Tools install"
  include_tasks: ../utils/win_shutdown_restart.yml
  vars:
    set_win_power_state: "restart"