# Copyright 2022-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Generate Autounattend.xml file from template to the temp path on local machine
- name: "Set fact of unattend file template path and dest path"
  ansible.builtin.set_fact:
    unattend_install_conf_path: "{{ main_playbook_path }}/autoinstall/{{ unattend_install_conf }}"
    unattend_dest_path: "{{ local_cache }}/{{ current_test_timestamp }}"

- name: "Set fact of target Autounattend.xml file path"
  ansible.builtin.set_fact:
    created_unattend_file: "{{ unattend_dest_path }}/Autounattend.xml"

- name: "Create directory of dest path for Autounattend.xml file"
  include_tasks: ../../common/create_directory.yml
  vars:
    dir_path: "{{ unattend_dest_path }}"

- name: "Set fact of the 'processorArchitecture' info in Autounattend.xml"
  ansible.builtin.set_fact:
    win_unattend_arch: >-
      {%- if (esxi_cpu_vendor | default('intel')) == 'arm' -%}arm64
      {%- elif guest_id is search('64') -%}amd64
      {%- else -%}x86
      {%- endif -%}

- name: "Generate encoded VM password"
  include_tasks: ../utils/win_gen_base64_password.yml
  vars:
    win_original_password: "{{ vm_password }}"
    win_append_string: Password

- name: "Set fact of the encoded VM password"
  ansible.builtin.set_fact:
    win_encoded_password: "{{ win_passwd_base64 }}"

- name: "Handle Administrator password"
  when: vm_username | lower == "administrator"
  block:
    - name: "Generate encoded VM password"
      include_tasks: ../utils/win_gen_base64_password.yml
      vars:
        win_original_password: "{{ vm_password }}"
        win_append_string: AdministratorPassword
    - name: "Set fact of the encoded VM administrator password"
      ansible.builtin.set_fact:
        win_encoded_admin_password: "{{ win_passwd_base64 }}"

- name: "Create unattend config file from template"
  ansible.builtin.template:
    src: "{{ unattend_install_conf_path }}"
    dest: "{{ created_unattend_file }}"
    mode: "0644"
  register: create_unattend_file_result

- name: "Display the result of generating unattend config file"
  ansible.builtin.debug: var=create_unattend_file_result
  when: enable_debug
