# Copyright 2021-2026 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Create the current test run log files path in specified dir or in default dir.
- name: "Set the log files path of this test run"
  when: not in_desktop_hypervisor_testing
  ansible.builtin.set_fact:
    testrun_log_path: "{{ local_log_path | default(main_playbook_path) }}/logs/{{ vm_name }}/{{ testrun_timestamp[:-4] }}"

- name: "Set the log files path of this test run"
  when: in_desktop_hypervisor_testing
  ansible.builtin.set_fact:
    testrun_log_path: "{{ local_log_path | default(main_playbook_path) }}/logs/{{ dh_vm_name | default('test_dh_vm') }}/{{ testrun_timestamp }}"

- name: "Create the log files directory locally with mode '0755'"
  ansible.builtin.file:
    path: "{{ testrun_log_path }}"
    state: directory
    mode: '0755'
  register: create_log_path
- ansible.builtin.debug: var=create_log_path
  when: enable_debug is defined and enable_debug

- name: "Print the path to test run logs"
  ansible.builtin.debug: var=testrun_log_path
