# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Check if specified file/object exists in Windows guest OS
# Parameters:
#   win_check_file_exist_file: the full path of the file/object to get
#     the facts of.
# Return:
#   win_check_file_exist_result: whether the specified file/object exists in
#     guest OS or not, returns true or false.
#
- name: "Initialize the file status"
  ansible.builtin.set_fact:
    win_check_file_exist_result: false

- name: "Check if specified file exists in Windows guest OS"
  ansible.windows.win_stat:
    path: "{{ win_check_file_exist_file }}"
    get_checksum: no
  delegate_to: "{{ vm_guest_ip }}"
  register: win_check_file_info
  ignore_errors: true
  become: "{{ win_check_file_become | default(false) }}"
  become_method: runas
  become_user: "{{ win_check_file_become_user | default('Administrator') }}"

- name: "Display the returned file info"
  ansible.builtin.debug: var=win_check_file_info
  when: enable_debug

- name: "Set fact of file existence"
  ansible.builtin.set_fact:
    win_check_file_exist_result: true
  when:
    - win_check_file_info.stat is defined
    - win_check_file_info.stat.exists is defined
    - win_check_file_info.stat.exists

- name: "Display the check result"
  ansible.builtin.debug:
    msg: "File '{{ win_check_file_exist_file }}' is in guest OS: {{ win_check_file_exist_result }}"
