# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Execute specified PowerShell command in Windows guest OS
# Parameters:
#   win_powershell_cmd: PowerShell command to be executed in guest OS.
#   win_execute_cmd_ignore_error: whether to ignore the failure returned
#     by executing command in guest OS. Default value is false.
#   win_execute_cmd_no_log: whether to print the output of executing command
#     task. Default value is false.
# Return:
#   win_powershell_cmd_output: the output of executing command task.
#
- name: "Check required parameter"
  ansible.builtin.assert:
    that:
      - win_powershell_cmd is defined
      - win_powershell_cmd
    fail_msg: "Parameter 'win_powershell_cmd' is not specified"

- name: "Initialize the command execution result"
  ansible.builtin.set_fact:
    win_powershell_cmd_output: ""

- name: "Execute PowerShell command"
  ansible.windows.win_shell: "{{ win_powershell_cmd }}"
  register: win_powershell_cmd_output
  ignore_errors: "{{ win_execute_cmd_ignore_error | default(false) }}"
  delegate_to: "{{ vm_guest_ip }}"
  ignore_unreachable: true
  no_log: "{{ win_execute_cmd_no_log | default(false) }}"
  become: "{{ win_execute_cmd_become | default(false) }}"
  become_method: runas
  become_user: "{{ win_execute_cmd_become_user | default('Administrator') }}"

- name: "Test network connection when guest OS unreachable"
  when:
    - win_powershell_cmd_output.unreachable is defined
    - win_powershell_cmd_output.unreachable
  block:
    - name: "Test network connection to VM"
      ansible.builtin.command: ping -c 10 "{{ vm_guest_ip }}"
      register: ping_vm_result
      changed_when: false
      ignore_errors: true
    - name: "Print the result of ping VM IP"
      ansible.builtin.debug: var=ping_vm_result

    - name: "Execute PowerShell command in guest OS failed"
      ansible.builtin.fail:
        msg: >-
          Executing PowerShell command '{{ win_powershell_cmd }}' task in guest OS failed
          due to guest OS is unreachable, and ping guest OS IP '{{ vm_guest_ip }}'
          {{ (ping_vm_result.rc | default(1) == 0) | ternary('passed', 'failed') }}.

- name: "Display the PowerShell command result"
  ansible.builtin.debug: var=win_powershell_cmd_output
  when: enable_debug
  no_log: "{{ win_execute_cmd_no_log | default(false) }}"
