# Copyright 2023 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Enable nested virtualization on host VM
- name: "Shutdown Linux host VM"
  when: host_machine_type == "linux"
  include_tasks: ../../linux/utils/shutdown.yml

- name: "Shutdown Windows host VM"
  when: host_machine_type == "windows"
  include_tasks: ../../windows/utils/win_shutdown_restart.yml
  vars:
    set_win_power_state: "shutdown"

- name: "Enable host VM nested virtualization"
  include_tasks: ../../common/vm_set_nested_virtual.yml
  vars:
    vm_nested_virt: true

- name: "Power on host VM"
  include_tasks: ../../common/vm_set_power_state.yml
  vars:
    vm_power_state_set: 'powered-on'

- name: "Update Ansible host inventory"
  when: host_machine_type == "linux"
  include_tasks: ../../common/update_inventory.yml

- name: "Update Ansible host inventory"
  when: host_machine_type == "windows"
  include_tasks: ../../windows/utils/win_update_inventory.yml

- name: "Set host machine IP to be variable 'vm_guest_ip' used in utils tasks"
  ansible.builtin.set_fact:
    host_machine_hostname: "{{ vm_guest_ip }}"
